### ISSUE TITLE
lspsaga popover text unreadable

### ISSUE THREAD

**Issue by lynndylanhurley** [shaunsingh/seoul256.nvim#2]
See screenshot:

<img width="611" alt="Screen Shot 2021-06-02 at 1 54 17 PM" src="https://user-images.githubusercontent.com/468037/120536885-3c646080-c3aa-11eb-8386-62b646bfd3fe.png">

**Comment by shaunsingh** [comment]
https://github.com/shaunsingh/seoul256.nvim/commit/c50bbc457dc08b250c5357477f2878661e9aef26, I changed the background of the LSPSaga menu to be the same as the regular bg. Let me know if it looks any better

**Comment by lynndylanhurley** [comment]
way better, thanks @shaunsingh!
