### ISSUE TITLE
Strings should use higher contrast color

### ISSUE THREAD

**Issue by lynndylanhurley** [shaunsingh/seoul256.nvim#3]
Currently strings use the same color as code comments (see attached). The original plugin uses blue for strings.

<img width="464" alt="Screen Shot 2021-06-02 at 9 59 39 AM" src="https://user-images.githubusercontent.com/468037/120537128-8b11fa80-c3aa-11eb-8338-0a7be3a1c892.png">

**Comment by shaunsingh** [comment]
https://github.com/shaunsingh/seoul256.nvim/pull/1 needs to go through first, after that I'll change the string color to blue

**Comment by shaunsingh** [comment]
Do you think the grey looks good enough or would you still prefer blue?

**Comment by lynndylanhurley** [comment]
Here's a comparison of the original theme and the latest from this theme:

Original seoul256.vim:
<img width="621" alt="Screen Shot 2021-06-02 at 8 47 34 PM" src="https://user-images.githubusercontent.com/468037/120573881-ef04e500-c3e3-11eb-8933-7a4fff49997a.png">

Latest seoul256.nvim:
<img width="635" alt="Screen Shot 2021-06-02 at 8 46 53 PM" src="https://user-images.githubusercontent.com/468037/120573909-f75d2000-c3e3-11eb-80a5-3ecb622b522d.png">

One of the things that I like about seoul256 is that even though the color palette is really subtle, it's able to create contrast between the different elements. I think the light blue stands out a little better against the background and the surrounding text.

**Comment by booperlv** [comment]
Have spent a few days writing a lot of code with this colorscheme, and I think this could be a nice change. I'm going to mess with this for a little while and see.

**Comment by shaunsingh** [comment]
Sorry for the delay, this should be fixed in the most recent commit (https://github.com/shaunsingh/seoul256.nvim/commit/e6101878ec046c5066a751d6d972c3977150d8d8). I made the indent line color grey as well to match the original theme. Feel free to let me know if I missed anything else

**Comment by lynndylanhurley** [comment]
Thanks @shaunsingh !! Trying it out now

**Comment by lynndylanhurley** [comment]
Just updated and now I'm getting this error:
```

**Comment by shaunsingh** [comment]
I forgot a comma, just fixed it. Sorry about that!

**Comment by shaunsingh** [comment]
As there hasn't been any activity in this issue for a while now, I'll be closing it. If you find any other colors to be inaccurate, or if there are any changes you would like me to implement, feel free to either re-open this issue or create a new one!
